### ISSUE TITLE
Windows doesn't support colons in filenames

### ISSUE THREAD

**Issue by chapulina** [gazebosim/gz-fuel-tools#106]
This makes several of our tests fail, because they try to create folders such as `localhost:8001` in the local cache.

Example failure:

```
Failed to copy file [D:\Jenkins\workspace\ignition_fuel-tools-ci-pr_any-windows7-amd64\ws\ign-fuel-tools\build\test_cache\localhost:8007\alice\models\My Model\2\model.config] to [D:\Jenkins\workspace\ignition_fuel-tools-ci-pr_any-windows7-amd64\ws\ign-fuel-tools\build\test_cache\localhost:8007\alice\models\My Model\3\model.config]: The filename, directory name, or volume label syntax is incorrect.
```

We could just change the tests, but this would also be a problem for a user who actually needs a port number in their servers. This will also be a problem for model names containing colons.

So for now I'll disable these tests on Windows until we come up with a better solution.

**Comment by mjcarroll** [comment]
Fixed by #376
