### ISSUE TITLE
:farmer: 7 failing tests in Windows due to colon in `common::joinPaths`

### ISSUE THREAD

**Issue by Crola1702** [gazebosim/gz-fuel-tools#307]
## Environment
* OS Version: 
  * Windows
* Source build
  * Fuel tools 8

## Description
* Expected behavior: Build passing successful
* Actual behavior: Build has 7 test regressions

## Steps to reproduce
1. Run a build in [ign_fuel-tools-gz-8-win](https://build.osrfoundation.org/job/ign_fuel-tools-gz-8-win/)
2. See 7 test regressions when you finish

### Fuel tools 8 Windows | Test regressions | Pending investigation :yellow_circle: 

Reference build: https://build.osrfoundation.org/job/ign_fuel-tools-gz-8-win/19/#showFailuresLink

Failing tests:
<details>

* [UNIT_gz_src_TEST.test_ran](https://build.osrfoundation.org/job/ign_fuel-tools-gz-8-win/19/testReport/junit/(root)/UNIT_gz_src_TEST/test_ran/)
* [FuelClientTest.CachedWorld](https://build.osrfoundation.org/job/ign_fuel-tools-gz-8-win/19/testReport/junit/(root)/FuelClientTest/CachedWorld/)
* [FuelClientTest.PatchModelFail](https://build.osrfoundation.org/job/ign_fuel-tools-gz-8-win/19/testReport/junit/(root)/FuelClientTest/PatchModelFail/)
* [LocalCacheTest.MatchingModels](https://build.osrfoundation.org/job/ign_fuel-tools-gz-8-win/19/testReport/junit/(root)/LocalCacheTest/MatchingModels/)
* [LocalCacheTest.MatchingModel](https://build.osrfoundation.org/job/ign_fuel-tools-gz-8-win/19/testReport/junit/(root)/LocalCacheTest/MatchingModel/)
* [LocalCacheTest.AllWorlds](https://build.osrfoundation.org/job/ign_fuel-tools-gz-8-win/19/testReport/junit/(root)/LocalCacheTest/AllWorlds/)
* [LocalCacheTest.MatchingWorlds](https://build.osrfoundation.org/job/ign_fuel-tools-gz-8-win/19/testReport/junit/(root)/LocalCacheTest/MatchingWorlds/)
* [LocalCacheTest.MatchingWorld](https://build.osrfoundation.org/job/ign_fuel-tools-gz-8-win/19/testReport/junit/(root)/LocalCacheTest/MatchingWorld/)

</details>

---

FuelClientTest output:
```
C:\Jenkins\workspace\ign_fuel-tools-gz-8-win\ws\gz-fuel-tools\src\FuelClient_TEST.cc:108
Value of: common::createDirectories(common::joinPaths(worldPath, "2"))
  Actual: false
Expected: true
```

LocalCacheTest output:
```
C:\Jenkins\workspace\ign_fuel-tools-gz-8-win\ws\gz-fuel-tools\src\LocalCache_TEST.cc:137
Value of: common::createDirectories(common::joinPaths(serverPath, "alice", "worlds", "am1", "2"))
  Actual: false
Expected: true
```

This test is probably failing because of [Windows doesn't support colons in filenames](https://github.com/gazebosim/gz-fuel-tools/issues/106) (reported 2 years ago).

Colon is used in this [line of code](https://github.com/gazebosim/gz-fuel-tools/blob/gz-fuel-tools8/src/FuelClient_TEST.cc#L106), and the test is failing 2 lines below:

```cpp
  auto worldPath = common::joinPaths(
      "test_cache", "localhost:8007", "banana", "worlds", "My World");

  ASSERT_TRUE(common::createDirectories(common::joinPaths(worldPath, "2")));
  ASSERT_TRUE(common::createDirectories(common::joinPaths(worldPath, "3")));
```

**Comment by azeey** [comment]
We need to replace the colon with something that's valid as a file name, but we're not sure what character.
Possible ideas:
- Replace with `.`
- base64 hash the host name.

**Comment by Crola1702** [comment]
Any new ideas? @nkoenig

**Comment by Crola1702** [comment]
> Any new ideas?

(Friendly ping @nkoenig)

**Comment by azeey** [comment]
Let's disable this for now.
