### ISSUE TITLE
Building Gazebo brings warning for gz-fuel-tools

### ISSUE THREAD

**Issue by ashkreli** [gazebosim/gz-fuel-tools#356]
I'm just following the suggestion given at the output; I hope it's of use to someone here.
Using Ubuntu 22.04 on a VM installing Gazebo Garden
I applied `colcon build --cmake-args -DBUILD_TESTING=OFF --merge-install`

I was building the Gazebo libraries as per https://gazebosim.org/docs/garden/install_ubuntu_src, and as it was building I came across:

    CMake Warning (dev) at /home/ashkreli/workspace/install/share/cmake/gz-cmake3/cmake3/GzFindPackage.cmake:456 (message):
       -- THIS MESSAGE IS INTENDED FOR GZ-FUEL_TOOLS AUTHORS --
          (IF YOU SEE THIS, PLEASE REPORT IT)
    
      Could not find pkg-config information for YAML.  It was not provided by the
      find-module for the package, nor was it explicitly passed into the call to
      gz_find_package(~).  This is most likely an error in this project's use of
      gz-cmake.
    Call Stack (most recent call first):
      CMakeLists.txt:44 (gz_find_package)
    This warning is for project developers.  Use -Wno-dev to suppress it. 

Also, before that I had gotten

    Starting >>> gz-physics6
    [Processing: gz-msgs9, gz-physics6, gz-rendering7]                       
    --- stderr: gz-rendering7                                                     
    CUDA_TOOLKIT_ROOT_DIR not found or specified
    CMake Warning at /home/ashkreli/workspace/install/share/cmake/gz-cmake3/cmake3/GzConfigureBuild.cmake:68 (message):
       CONFIGURATION WARNINGS:
       -- Skipping component [optix]: Missing dependency [OptiX].
          ^~~~~ Set SKIP_optix=true in cmake to suppress this warning.
       
    Call Stack (most recent call first):
      CMakeLists.txt:188 (gz_configure_build)

I'm not sure if it is related but figured to mention it.

**Comment by mjcarroll** [comment]
Looking at the warning, I think that you may have skipped this step:

```
sudo apt -y install \
  $(sort -u $(find . -iname 'packages-'`lsb_release -cs`'.apt' -o -iname 'packages.apt' | grep -v '/\.git/') | sed '/gz\|sdf/d' | tr '\n' ' ')
```

The dependency is defined here: https://github.com/gazebosim/gz-fuel-tools/blob/9036b5863d513a7ce9dd2a06cf73c946ad5c75e3/.github/ci/packages.apt#L12

Alternatively, you can install with `sudo apt install libyaml-dev`

> I'm not sure if it is related but figured to mention it.

The `optix` warning is unrelated and only appears if you don't have optix installed/available on your system.  You can suppress this in the future via:

```
colcon build --cmake-args -DBUILD_TESTING=OFF -DSKIP_optix=true --merge-install
```
