### ISSUE TITLE
:farmer: `CollectionTest/DownloadCollectionTest` failing in Citadel Bionic, Windows and Homebrew

### ISSUE THREAD

**Issue by Crola1702** [gazebosim/gz-fuel-tools#391]
## Environment
* OS Version: Ubuntu Bionic, Windows and Homebrew
* Source gz-fuel_tools4 bionic

## Description
* Expected behavior: All test should pass
* Actual behavior: `CollectionTest/DownloadCollectionTest` tests are failing

## Steps to reproduce
1. Run a build in [gz-fuel_tools4 bionic](https://build.osrfoundation.org/job/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/) or [gz-fuel_tools4 windows](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/)
2. See tests fail

## Output

Reference builds:
* https://build.osrfoundation.org/job/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/9/
* https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/

<details>
<summary>
Bionic test regressions:
</summary>

[CollectionTest/DownloadCollectionTest.AllItems/0](https://build.osrfoundation.org/job/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/9/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/AllItems_0/)
[CollectionTest/DownloadCollectionTest.AllItems/1](https://build.osrfoundation.org/job/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/9/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/AllItems_1/)
[CollectionTest/DownloadCollectionTest.AllItems/2](https://build.osrfoundation.org/job/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/9/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/AllItems_2/)
[CollectionTest/DownloadCollectionTest.Models/0](https://build.osrfoundation.org/job/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/9/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/Models_0/)
[CollectionTest/DownloadCollectionTest.Models/1](https://build.osrfoundation.org/job/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/9/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/Models_1/)
[CollectionTest/DownloadCollectionTest.Models/2](https://build.osrfoundation.org/job/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/9/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/Models_2/)

</details>

<details>
<summary>
Log output bionic:
</summary>

```
7: [Dbg] [LocalCache.cc:598] Model [backpack] loading resource from another model, named [Backpack]. On Blueprint (ign-fuel-tools 3) and Citadel (ign-fuel-tools 4), [Backpack] is ignored. From Dome (ign-fuel-tools 5), [backpack] will be used. If [Backpack] is not a model belonging to owner [openrobotics], fix your SDF file!
7: [Dbg] [LocalCache.cc:598] Model [backpack] loading resource from another model, named [Backpack]. On Blueprint (ign-fuel-tools 3) and Citadel (ign-fuel-tools 4), [Backpack] is ignored. From Dome (ign-fuel-tools 5), [backpack] will be used. If [Backpack] is not a model belonging to owner [openrobotics], fix your SDF file!
7: [Msg] Finished, downloaded 2 models in total
7: /home/jenkins/workspace/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/ign-fuel-tools/src/gz_src_TEST.cc:463: Failure
7: Value of: common::isDirectory( common::joinPaths(this->testCachePath, "fuel.gazebosim.org", "openrobotics", "models", "backpack", "2"))
7:   Actual: false
7: Expected: true
7: /home/jenkins/workspace/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/ign-fuel-tools/src/gz_src_TEST.cc:466: Failure
7: Value of: common::isFile( common::joinPaths(this->testCachePath, "fuel.gazebosim.org", "openrobotics", "models", "backpack", "2", "model.sdf"))
7:   Actual: false
7: Expected: true
7: /home/jenkins/workspace/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/ign-fuel-tools/src/gz_src_TEST.cc:474: Failure
7: Value of: common::isDirectory( common::joinPaths(this->testCachePath, "fuel.gazebosim.org", "openrobotics", "models", "teambase", "2"))
7:   Actual: false
7: Expected: true
7: /home/jenkins/workspace/ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64/ign-fuel-tools/src/gz_src_TEST.cc:477: Failure
7: Value of: common::isFile( common::joinPaths(this->testCachePath, "fuel.gazebosim.org", "openrobotics", "models", "teambase", "2", "model.sdf"))
7:   Actual: false
7: Expected: true
7: [  FAILED  ] CollectionTest/DownloadCollectionTest.Models/2, where GetParam() = 16 (1717 ms)
```

</details>

<details>
<summary>
Windows test regressions:
</summary>

[CmdLine.ModelListFail](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CmdLine/ModelListFail/)
[CmdLine.ModelDownloadBadUrl](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CmdLine/ModelDownloadBadUrl/)
[CmdLine.ModelDownloadWrongUrl](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CmdLine/ModelDownloadWrongUrl/)
[CmdLine.ModelDownloadUnversioned](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CmdLine/ModelDownloadUnversioned/)
[CmdLine.DownloadConfigCache](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CmdLine/DownloadConfigCache/)
[CmdLine.WorldListFail](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CmdLine/WorldListFail/)
[CmdLine.WorldDownloadBadUrl](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CmdLine/WorldDownloadBadUrl/)
[CmdLine.WorldDownloadWrongUrl](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CmdLine/WorldDownloadWrongUrl/)
[CmdLine.WorldDownloadUnversioned](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CmdLine/WorldDownloadUnversioned/)
[CollectionTest/DownloadCollectionTest.Worlds/0](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/Worlds_0/)
[CollectionTest/DownloadCollectionTest.Worlds/1](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/Worlds_1/)
[CollectionTest/DownloadCollectionTest.Worlds/2](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/Worlds_2/)
[CollectionTest/DownloadCollectionTest.AllItems/0](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/AllItems_0/)
[CollectionTest/DownloadCollectionTest.AllItems/1](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/AllItems_1/)
[CollectionTest/DownloadCollectionTest.AllItems/2](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/AllItems_2/)
[CollectionTest/DownloadCollectionTest.Models/0](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/Models_0/)
[CollectionTest/DownloadCollectionTest.Models/1](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/Models_1/)
[CollectionTest/DownloadCollectionTest.Models/2](https://build.osrfoundation.org/job/ign_fuel-tools-ign-4-win/97/testReport/junit/(root)/CollectionTest_DownloadCollectionTest/Models_2/)

</details>

<details>
<summary>
Log output windows:
</summary>

```
7: [ RUN      ] CollectionTest/DownloadCollectionTest.Worlds/2
7: C:\J\workspace\ign_fuel-tools-ign-4-win\ws\gz-fuel-tools\src\gz_src_TEST.cc(505): error: Value of: this->stdErrBuffer.str().empty()
7:   Actual: false
7: Expected: true
7: [31m[Err] [C:\J\workspace\ign_fuel-tools-ign-4-win\ws\gz-common\src\Filesystem.cc:469] [m[31m[Err] [C:\J\workspace\ign_fuel-tools-ign-4-win\ws\gz-common\src\Filesystem.cc:469] [m[31m[Err] [C:\J\workspace\ign_fuel-tools-ign-4-win\ws\gz-common\src\Filesystem.cc:469] [m[31m[Err] [C:\J\workspace\ign_fuel-tools-ign-4-win\ws\gz-common\src\Filesystem.cc:469] [m[31m[Err] [C:\J\workspace\ign_fuel-tools-ign-4-win\ws\gz-common\src\Filesystem.cc:469] [m
7: [  FAILED  ] CollectionTest/DownloadCollectionTest.Worlds/2, where GetParam() = 16 (950 ms)
```

</details>

This is related to: https://github.com/gazebosim/gz-fuel-tools/issues/340 and https://github.com/gazebosim/gz-fuel-tools/issues/370. But I can't figure out the fix right away :thinking:

**Comment by mjcarroll** [comment]
Closed by #392
